//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        public customers()
        {
            this.orders = new HashSet<orders>();
            this.payments = new HashSet<payments>();
        }
    
        public int customerNumber { get; set; }
        public string customerName { get; set; }
        public string contactLastName { get; set; }
        public string contactFirstName { get; set; }
        public string phone { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postalCode { get; set; }
        public string country { get; set; }
        public Nullable<int> salesRepEmployeeNumber { get; set; }
        public Nullable<double> creditLimit { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual ICollection<orders> orders { get; set; }
        public virtual ICollection<payments> payments { get; set; }
    }
}
