//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.itemimage = new HashSet<itemimage>();
            this.order_detail = new HashSet<order_detail>();
            this.showcaseitem = new HashSet<showcaseitem>();
        }
    
        public string itemID { get; set; }
        public string tenantID { get; set; }
        public string itemName { get; set; }
        public string itemDesc { get; set; }
        public float unitPrice { get; set; }
    
        public virtual tenant tenant { get; set; }
        public virtual ICollection<itemimage> itemimage { get; set; }
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual ICollection<showcaseitem> showcaseitem { get; set; }
    }
}
