//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.itemimage = new HashSet<itemimage>();
            this.showcaseitem = new HashSet<showcaseitem>();
            this.suborder = new HashSet<suborder>();
        }
    
        public string itemID { get; set; }
        public string tenantID { get; set; }
        public string itemName { get; set; }
        public string itemDesc { get; set; }
        public int itemQty { get; set; }
        public float unitPrice { get; set; }
        public sbyte availability { get; set; }
    
        public virtual tenant tenant { get; set; }
        public virtual ICollection<itemimage> itemimage { get; set; }
        public virtual ICollection<showcaseitem> showcaseitem { get; set; }
        public virtual ICollection<suborder> suborder { get; set; }
    }
}
