//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<attendence> attendence { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<item> item { get; set; }
        public DbSet<itemimage> itemimage { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<order_detail> order_detail { get; set; }
        public DbSet<rentinfo> rentinfo { get; set; }
        public DbSet<reservation> reservation { get; set; }
        public DbSet<showcase> showcase { get; set; }
        public DbSet<showcaseitem> showcaseitem { get; set; }
        public DbSet<staff> staff { get; set; }
        public DbSet<tenant> tenant { get; set; }
    }
}
