//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class spdEntities : DbContext
    {
        public spdEntities()
            : base("name=spdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customer> customer { get; set; }
        public DbSet<item> item { get; set; }
        public DbSet<itemimage> itemimage { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<rentinfo> rentinfo { get; set; }
        public DbSet<reservation> reservation { get; set; }
        public DbSet<showcase> showcase { get; set; }
        public DbSet<showcaseitem> showcaseitem { get; set; }
        public DbSet<suborder> suborder { get; set; }
        public DbSet<tenant> tenant { get; set; }
    }
}
