//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sdpEntities : DbContext
    {
        public sdpEntities()
            : base("name=sdpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<attendence> attendences { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<itemimage> itemimages { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<order_detail> order_detail { get; set; }
        public DbSet<preinputitem> preinputitems { get; set; }
        public DbSet<rentinfo> rentinfoes { get; set; }
        public DbSet<reservation> reservations { get; set; }
        public DbSet<showcase> showcases { get; set; }
        public DbSet<showcaseitem> showcaseitems { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<tenant> tenants { get; set; }
    }
}
