//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.suborder = new HashSet<suborder>();
        }
    
        public int orderID { get; set; }
        public int customerID { get; set; }
        public System.DateTime orderDate { get; set; }
    
        public virtual ICollection<suborder> suborder { get; set; }
    }
}
