//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.order_detail = new HashSet<order_detail>();
        }
    
        public string orderID { get; set; }
        public string storeID { get; set; }
        public string customerID { get; set; }
        public System.DateTime orderDate { get; set; }
        public float orderTotalPrice { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual store store { get; set; }
    }
}
