//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class preinputitem
    {
        public string preinputitemid { get; set; }
        public string itemname { get; set; }
        public int itemqty { get; set; }
        public string itemdesc { get; set; }
        public float itemunitprice { get; set; }
        public string tenantid { get; set; }
    }
}
