//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.orderdetails = new HashSet<orderdetails>();
        }
    
        public string productCode { get; set; }
        public string productName { get; set; }
        public string productLine { get; set; }
        public string productScale { get; set; }
        public string productVendor { get; set; }
        public string productDescription { get; set; }
        public short quantityInStock { get; set; }
        public double buyPrice { get; set; }
        public double MSRP { get; set; }
    
        public virtual ICollection<orderdetails> orderdetails { get; set; }
        public virtual productlines productlines { get; set; }
    }
}
