//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentinfo
    {
        public int rentID { get; set; }
        public int tenantID { get; set; }
        public System.DateTime startDate { get; set; }
        public int duration { get; set; }
    
        public virtual tenant tenant { get; set; }
    }
}
