//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class showcaseitem
    {
        public string showcaseid { get; set; }
        public string storeID { get; set; }
        public string itemid { get; set; }
        public int availableQty { get; set; }
        public int soldQty { get; set; }
        public int TotalQty { get; set; }
        public Nullable<sbyte> availability { get; set; }
    
        public virtual item item { get; set; }
        public virtual showcase showcase { get; set; }
        public virtual store store { get; set; }
    }
}
