//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class showcase
    {
        public showcase()
        {
            this.rentinfoes = new HashSet<rentinfo>();
            this.showcaseitems = new HashSet<showcaseitem>();
        }
    
        public string showcaseid { get; set; }
        public int size { get; set; }
        public float rental { get; set; }
        public string status { get; set; }
        public sbyte availability { get; set; }
        public string storeID { get; set; }
    
        public virtual ICollection<rentinfo> rentinfoes { get; set; }
        public virtual ICollection<showcaseitem> showcaseitems { get; set; }
        public virtual store store { get; set; }
    }
}
