//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenant
    {
        public tenant()
        {
            this.item = new HashSet<item>();
            this.rentinfo = new HashSet<rentinfo>();
        }
    
        public string tenantID { get; set; }
        public string tenantpwd { get; set; }
        public string tenantName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<item> item { get; set; }
        public virtual ICollection<rentinfo> rentinfo { get; set; }
    }
}
