//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenant
    {
        public tenant()
        {
            this.items = new HashSet<item>();
            this.preinputitems = new HashSet<preinputitem>();
            this.rentinfoes = new HashSet<rentinfo>();
            this.reservations = new HashSet<reservation>();
        }
    
        public string tenantID { get; set; }
        public string tenantpwd { get; set; }
        public string tenantName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        public virtual ICollection<item> items { get; set; }
        public virtual ICollection<preinputitem> preinputitems { get; set; }
        public virtual ICollection<rentinfo> rentinfoes { get; set; }
        public virtual ICollection<reservation> reservations { get; set; }
    }
}
