//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDP_SE1A_Group2
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemimage
    {
        public string itemImageID { get; set; }
        public string filename { get; set; }
        public byte[] picture { get; set; }
        public string itemID { get; set; }
    
        public virtual item item { get; set; }
    }
}
